site_name: SoftArch B24
theme:
  name: material
  palette:
    primary: deep orange
    accent: amber
    scheme: slate
  icon:
    repo: fontawesome/brands/github-alt

extra:
  version:
    provider: mike

plugins:
  - offline
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/subatiq/softarch-b24
